;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="GameplayCue.Burn",DevComment="")
+GameplayTagList=(Tag="GameplayCue.HealthPickup",DevComment="")
+GameplayTagList=(Tag="MobaFlex.Character.Burn",DevComment="")
+GameplayTagList=(Tag="MobaFlex.Character.NoArmor",DevComment="")
+GameplayTagList=(Tag="MobaFlex.Character.NoHealth",DevComment="")
+GameplayTagList=(Tag="MobaFlex.Character.NoMana",DevComment="")
+GameplayTagList=(Tag="MobaFlex.Character.NoStamina",DevComment="")
+GameplayTagList=(Tag="MobaFlex.Character.Sprint",DevComment="")

